export const Users = [
    {
        id:1,
        profilePicture: "/assets/images/2.jpeg",
        username: "Nicole Rose",
    },
    {
        id:2,
        profilePicture: "/assets/images/1.jpeg",
        username: "Nicole Rose",
    },
    {
        id:3,
        profilePicture: "/assets/images/3.jpeg",
        username: "Max joe",
    },
    {
        id:4,
        profilePicture: "/assets/images/2.jpeg",
        username: "Robin Joe",
    },
    {
        id:5,
        profilePicture: "/assets/images/2.jpeg",
        username: "Robin Joe",
    },
    {
        id:6,
        profilePicture: "/assets/images/3.jpeg",
        username: "Max joe",
    },
    {
        id:7,
        profilePicture: "/assets/images/1.jpeg",
        username: "Nicole Rose",
    },
]
export const Posts =[
    {
        id: 1,
        desc: "Finished Jkuat.",
        photo: "/assets/images/1.jpeg",
        date: "5 minutes ago",
        userId: 1,
        like: 32,
        Comment: 9,
    },
    {
        id: 2,
        photo: "/assets/images/3.jpeg",
        date: "15 minutes ago",
        userId: 2,
        like: 2,
        Comment: 9,
    },
    {
        id: 3,
        desc: "#longLive",
        photo: "/assets/images/3.jpeg",
        date: "2 ago",
        userId: 3,
        like: 321,
        Comment: 90,
    },
    {
        id: 4,
        desc: "sunday",
        photo: "/assets/images/1.jpeg",
        date: "2 hours ago",
        userId: 4,
        like: 31,
        Comment: 4,
    },
    {
        id: 5,
        desc: "monda",
        photo: "/assets/images/3.jpeg",
        date: "8 hours ago",
        userId: 5,
        like: 13,
        Comment: 9,
    },
    {
        id: 6,
        desc: "zvdv",
        photo: "/assets/images/1.jpeg",
        date: "9 hours ago",
        userId: 6,
        like: 13,
        Comment: 9,
    },
    {
        id: 7,
        desc: "zz c z czvdv",
        photo: "/assets/images/4.jpeg",
        date: "10 hours ago",
        userId: 7,
        like: 13,
        Comment: 9,
    },
]
